name: Update Version

on:
  push:
    branches:
      - development

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Version Update Script
      run: |
        # Go to the root directory of the repository
        cd $GITHUB_WORKSPACE

        # Run your version update script
        ./bump_version.sh
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
