name: Update Version

on:
  push:
    branches:
      - development

jobs:
  update-version:
    runs-on: ubuntu-latest

  
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run Version Update Script
      run: |
        # Go to the root directory of the repository
        cd $GITHUB_WORKSPACE

        # Run your version update script
        ./bump_version.sh

        # Set the user name
        git config --global user.name "SchoolyB"

        # Set the user email from the secret
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}

        # Add and commit the changes
        git add VERSION.txt
        git commit -m "Bump build version"
        git push
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}